name: Test All Builds

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Default Build (LineageOS)
          - name: LineageOS
            kernel_type: LineageOS

            susfs_support: true
            bbg_support: true
            susfs_force: false
            droidspaces_support: true
            extra_patches_dir: patches/droidspaces
            extra_configs: 'vendor/waipio_GKI.config vendor/nothing/waipio_GKI.config vendor/debugfs.config'

    uses: ./.github/workflows/build.yml
    with:
      kernel_type: ${{ matrix.kernel_type }}
      kernel_repo: ${{ matrix.kernel_repo || '' }}
      kernel_branch: ${{ matrix.kernel_branch || 'lineage-23.2' }}
      kernel_defconfig: ${{ matrix.kernel_defconfig || 'gki_defconfig' }}
      extra_configs: ${{ matrix.extra_configs || '' }}
      extra_patches_dir: ${{ matrix.extra_patches_dir || '' }}
      susfs_support: ${{ matrix.susfs_support }}
      bbg_support: ${{ matrix.bbg_support }}
      susfs_force: ${{ matrix.susfs_force }}
